"""agent key agreement for sealing

Revision ID: 0f9cd5cb0140
Revises: a1f7c0d4b2e9
Create Date: 2026-10-06 12:27:21.259995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f9cd5cb0140'
down_revision: Union[str, Sequence[str], None] = 'a1f7c0d4b2e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('kex_public_key', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'kex_public_key')
    # ### end Alembic commands ###
