"""reports and vuln remediation

Revision ID: 11b5687c2b37
Revises: 1fac2ea2db29
Create Date: 2026-10-04 20:57:12.661398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11b5687c2b37'
down_revision: Union[str, Sequence[str], None] = '1fac2ea2db29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('fmt', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('emailed_to', sa.String(length=255), nullable=True),
    sa.Column('email_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_reports_project_status', ['project_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_status'), ['status'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('slack_delivery',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               nullable=False)

    with op.batch_alter_table('vulns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remediation', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulns', schema=None) as batch_op:
        batch_op.drop_column('remediation')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('slack_delivery',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'site'"),
               nullable=True)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_status'))
        batch_op.drop_index('ix_reports_project_status')
        batch_op.drop_index(batch_op.f('ix_reports_project_id'))
        batch_op.drop_index(batch_op.f('ix_reports_kind'))

    op.drop_table('reports')
    # ### end Alembic commands ###
