"""baseline schema

Revision ID: 1fac2ea2db29
Revises:
Create Date: 2026-10-04 20:35:24.008107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fac2ea2db29'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groups_name'), ['name'], unique=True)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('client', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('slack_token', sa.Text(), nullable=True),
    sa.Column('slack_channel', sa.String(length=128), nullable=True),
    sa.Column('slack_delivery', sa.String(length=16), nullable=False),
    sa.Column('agent_provider', sa.String(length=16), nullable=True),
    sa.Column('agent_anthropic_token', sa.Text(), nullable=True),
    sa.Column('agent_openai_token', sa.Text(), nullable=True),
    sa.Column('agent_model', sa.String(length=128), nullable=True),
    sa.Column('slack_private', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_projects_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('google_sub', sa.String(length=64), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_google_sub'), ['google_sub'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('prefix', sa.String(length=12), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_prefix'), ['prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_revoked'), ['revoked'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_user_id'), ['user_id'], unique=False)

    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('service', sa.String(length=128), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('secret', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('validated', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credentials_host'), ['host'], unique=False)
        batch_op.create_index(batch_op.f('ix_credentials_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_credentials_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_credentials_project_user', ['project_id', 'username'], unique=False)
        batch_op.create_index(batch_op.f('ix_credentials_validated'), ['validated'], unique=False)

    op.create_table('domain_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('root_domain', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('times_seen', sa.Integer(), nullable=False),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_domcand_project_name')
    )
    with op.batch_alter_table('domain_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domain_candidates_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_domain_candidates_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_domain_candidates_root_domain'), ['root_domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_domain_candidates_score'), ['score'], unique=False)
        batch_op.create_index(batch_op.f('ix_domain_candidates_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_domain_candidates_state'), ['state'], unique=False)
        batch_op.create_index('ix_domcand_project_state', ['project_id', 'state'], unique=False)

    op.create_table('domain_searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('runs', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('candidates_found', sa.Integer(), nullable=False),
    sa.Column('known_at_last_run', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'domain', name='uq_domsearch_project_domain')
    )
    with op.batch_alter_table('domain_searches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domain_searches_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_domain_searches_project_id'), ['project_id'], unique=False)

    op.create_table('magic_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('magic_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_magic_links_token_hash'), ['token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_magic_links_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_magic_user_exp', ['user_id', 'expires_at'], unique=False)

    op.create_table('project_acls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(user_id IS NOT NULL AND group_id IS NULL) OR (user_id IS NULL AND group_id IS NOT NULL)', name='ck_acl_exactly_one_subject'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'group_id', name='uq_acl_project_group'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_acl_project_user')
    )
    with op.batch_alter_table('project_acls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_acls_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_acls_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_acls_user_id'), ['user_id'], unique=False)

    op.create_table('project_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('primary_contact', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_contacts_project_id'), ['project_id'], unique=False)

    op.create_table('project_scope',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('included', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'value', name='uq_scope_project_value')
    )
    with op.batch_alter_table('project_scope', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_scope_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_scope_project_kind', ['project_id', 'kind'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('alive', sa.Boolean(), nullable=True),
    sa.Column('hacked', sa.Boolean(), nullable=False),
    sa.Column('os', sa.String(length=255), nullable=True),
    sa.Column('os_accuracy', sa.Integer(), nullable=True),
    sa.Column('mac_address', sa.String(length=32), nullable=True),
    sa.Column('mac_vendor', sa.String(length=128), nullable=True),
    sa.Column('hostnames', sa.Text(), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'host', name='uq_target_project_host')
    )
    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_targets_alive'), ['alive'], unique=False)
        batch_op.create_index(batch_op.f('ix_targets_hacked'), ['hacked'], unique=False)
        batch_op.create_index(batch_op.f('ix_targets_host'), ['host'], unique=False)
        batch_op.create_index(batch_op.f('ix_targets_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index('ix_targets_project_host', ['project_id', 'host'], unique=False)
        batch_op.create_index(batch_op.f('ix_targets_project_id'), ['project_id'], unique=False)

    op.create_table('user_groups',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_kind'), ['kind'], unique=False)
        batch_op.create_index('ix_events_target_at', ['target_id', 'at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_target_id'), ['target_id'], unique=False)

    op.create_table('implants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('framework', sa.String(length=32), nullable=False),
    sa.Column('implant_id', sa.String(length=128), nullable=False),
    sa.Column('listener', sa.String(length=255), nullable=True),
    sa.Column('user', sa.String(length=255), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('process', sa.String(length=255), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('arch', sa.String(length=32), nullable=True),
    sa.Column('integrity', sa.String(length=16), nullable=True),
    sa.Column('internal_ip', sa.String(length=45), nullable=True),
    sa.Column('external_ip', sa.String(length=45), nullable=True),
    sa.Column('os', sa.String(length=255), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_id', 'framework', 'implant_id', name='uq_implant_target_fw_id')
    )
    with op.batch_alter_table('implants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_implants_framework'), ['framework'], unique=False)
        batch_op.create_index(batch_op.f('ix_implants_target_id'), ['target_id'], unique=False)

    op.create_table('pocs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pocs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pocs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pocs_target_id'), ['target_id'], unique=False)

    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=8), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('product', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=128), nullable=True),
    sa.Column('extrainfo', sa.String(length=255), nullable=True),
    sa.Column('tunnel', sa.String(length=32), nullable=True),
    sa.Column('method', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('cpe', sa.Text(), nullable=True),
    sa.Column('reason', sa.String(length=64), nullable=True),
    sa.Column('scripts', sa.Text(), nullable=True),
    sa.Column('banner', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_id', 'port', 'protocol', name='uq_service_target_port_proto')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index('ix_services_state', ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_target_id'), ['target_id'], unique=False)

    op.create_table('vulns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=8), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vulns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vulns_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulns_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulns_target_id'), ['target_id'], unique=False)
        batch_op.create_index('ix_vulns_target_sev', ['target_id', 'severity'], unique=False)

    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actions_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_service_id'), ['service_id'], unique=False)
        batch_op.create_index('ix_actions_service_status', ['service_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_status'), ['status'], unique=False)

    op.create_table('web_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('scheme', sa.String(length=8), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=True),
    sa.Column('webserver', sa.String(length=255), nullable=True),
    sa.Column('tech', sa.Text(), nullable=True),
    sa.Column('sources', sa.String(length=255), nullable=True),
    sa.Column('crawled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_id', 'url', name='uq_weburl_target_url')
    )
    with op.batch_alter_table('web_addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_web_addresses_crawled'), ['crawled'], unique=False)
        batch_op.create_index(batch_op.f('ix_web_addresses_path'), ['path'], unique=False)
        batch_op.create_index(batch_op.f('ix_web_addresses_port'), ['port'], unique=False)
        batch_op.create_index(batch_op.f('ix_web_addresses_status_code'), ['status_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_web_addresses_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_web_addresses_url'), ['url'], unique=False)
        batch_op.create_index('ix_weburl_target_status', ['target_id', 'status_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_addresses', schema=None) as batch_op:
        batch_op.drop_index('ix_weburl_target_status')
        batch_op.drop_index(batch_op.f('ix_web_addresses_url'))
        batch_op.drop_index(batch_op.f('ix_web_addresses_target_id'))
        batch_op.drop_index(batch_op.f('ix_web_addresses_status_code'))
        batch_op.drop_index(batch_op.f('ix_web_addresses_port'))
        batch_op.drop_index(batch_op.f('ix_web_addresses_path'))
        batch_op.drop_index(batch_op.f('ix_web_addresses_crawled'))

    op.drop_table('web_addresses')
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actions_status'))
        batch_op.drop_index('ix_actions_service_status')
        batch_op.drop_index(batch_op.f('ix_actions_service_id'))
        batch_op.drop_index(batch_op.f('ix_actions_kind'))

    op.drop_table('actions')
    with op.batch_alter_table('vulns', schema=None) as batch_op:
        batch_op.drop_index('ix_vulns_target_sev')
        batch_op.drop_index(batch_op.f('ix_vulns_target_id'))
        batch_op.drop_index(batch_op.f('ix_vulns_severity'))
        batch_op.drop_index(batch_op.f('ix_vulns_external_id'))

    op.drop_table('vulns')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_target_id'))
        batch_op.drop_index('ix_services_state')

    op.drop_table('services')
    with op.batch_alter_table('pocs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pocs_target_id'))
        batch_op.drop_index(batch_op.f('ix_pocs_status'))

    op.drop_table('pocs')
    with op.batch_alter_table('implants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_implants_target_id'))
        batch_op.drop_index(batch_op.f('ix_implants_framework'))

    op.drop_table('implants')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_target_id'))
        batch_op.drop_index('ix_events_target_at')
        batch_op.drop_index(batch_op.f('ix_events_kind'))
        batch_op.drop_index(batch_op.f('ix_events_at'))

    op.drop_table('events')
    op.drop_table('user_groups')
    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_targets_project_id'))
        batch_op.drop_index('ix_targets_project_host')
        batch_op.drop_index(batch_op.f('ix_targets_ip_address'))
        batch_op.drop_index(batch_op.f('ix_targets_host'))
        batch_op.drop_index(batch_op.f('ix_targets_hacked'))
        batch_op.drop_index(batch_op.f('ix_targets_alive'))

    op.drop_table('targets')
    op.drop_table('settings')
    with op.batch_alter_table('project_scope', schema=None) as batch_op:
        batch_op.drop_index('ix_scope_project_kind')
        batch_op.drop_index(batch_op.f('ix_project_scope_project_id'))

    op.drop_table('project_scope')
    with op.batch_alter_table('project_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_contacts_project_id'))

    op.drop_table('project_contacts')
    with op.batch_alter_table('project_acls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_acls_user_id'))
        batch_op.drop_index(batch_op.f('ix_project_acls_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_acls_group_id'))

    op.drop_table('project_acls')
    with op.batch_alter_table('magic_links', schema=None) as batch_op:
        batch_op.drop_index('ix_magic_user_exp')
        batch_op.drop_index(batch_op.f('ix_magic_links_user_id'))
        batch_op.drop_index(batch_op.f('ix_magic_links_token_hash'))

    op.drop_table('magic_links')
    with op.batch_alter_table('domain_searches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domain_searches_project_id'))
        batch_op.drop_index(batch_op.f('ix_domain_searches_domain'))

    op.drop_table('domain_searches')
    with op.batch_alter_table('domain_candidates', schema=None) as batch_op:
        batch_op.drop_index('ix_domcand_project_state')
        batch_op.drop_index(batch_op.f('ix_domain_candidates_state'))
        batch_op.drop_index(batch_op.f('ix_domain_candidates_source'))
        batch_op.drop_index(batch_op.f('ix_domain_candidates_score'))
        batch_op.drop_index(batch_op.f('ix_domain_candidates_root_domain'))
        batch_op.drop_index(batch_op.f('ix_domain_candidates_project_id'))
        batch_op.drop_index(batch_op.f('ix_domain_candidates_name'))

    op.drop_table('domain_candidates')
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credentials_validated'))
        batch_op.drop_index('ix_credentials_project_user')
        batch_op.drop_index(batch_op.f('ix_credentials_project_id'))
        batch_op.drop_index(batch_op.f('ix_credentials_kind'))
        batch_op.drop_index(batch_op.f('ix_credentials_host'))

    op.drop_table('credentials')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_revoked'))
        batch_op.drop_index(batch_op.f('ix_api_keys_prefix'))

    op.drop_table('api_keys')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_google_sub'))

    op.drop_table('users')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_status'))
        batch_op.drop_index(batch_op.f('ix_projects_code'))

    op.drop_table('projects')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_name'))

    op.drop_table('groups')
    # ### end Alembic commands ###
