"""web packet capture

Revision ID: 2ec46c880874
Revises: 8f1756228abb
Create Date: 2026-10-04 21:57:25.188927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ec46c880874'
down_revision: Union[str, Sequence[str], None] = '8f1756228abb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('method', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('request', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('response', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('truncated', sa.Boolean(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_web_addresses_method'), ['method'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_web_addresses_method'))
        batch_op.drop_column('truncated')
        batch_op.drop_column('response')
        batch_op.drop_column('request')
        batch_op.drop_column('method')

    # ### end Alembic commands ###
