"""cloud target provider

Revision ID: 35382e50c5b6
Revises: ebcf99e4d321
Create Date: 2026-10-05 08:03:01.766313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35382e50c5b6'
down_revision: Union[str, Sequence[str], None] = 'ebcf99e4d321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_targets_provider'), ['provider'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_targets_provider'))
        batch_op.drop_column('provider')

    # ### end Alembic commands ###
