"""jaws agents and tasking

Revision ID: 417056b3738b
Revises: 35382e50c5b6
Create Date: 2026-10-05 17:40:16.221993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '417056b3738b'
down_revision: Union[str, Sequence[str], None] = '35382e50c5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('callback_key_hash', sa.String(length=128), nullable=False),
    sa.Column('call_in_key_hash', sa.String(length=128), nullable=True),
    sa.Column('call_in_url', sa.String(length=300), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=True),
    sa.Column('arch', sa.String(length=16), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('privileged', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('tools', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='offline', nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_ip', sa.String(length=45), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_agents_project_status', ['project_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_status'), ['status'], unique=False)

    op.create_table('agent_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('args', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='queued', nullable=False),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('import_as', sa.String(length=32), nullable=True),
    sa.Column('import_result', sa.Text(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_tasks_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index('ix_agent_tasks_agent_status', ['agent_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_tasks_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_tasks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_tasks_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_agent_tasks_project_id'))
        batch_op.drop_index(batch_op.f('ix_agent_tasks_kind'))
        batch_op.drop_index('ix_agent_tasks_agent_status')
        batch_op.drop_index(batch_op.f('ix_agent_tasks_agent_id'))

    op.drop_table('agent_tasks')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_status'))
        batch_op.drop_index('ix_agents_project_status')
        batch_op.drop_index(batch_op.f('ix_agents_project_id'))
        batch_op.drop_index(batch_op.f('ix_agents_name'))

    op.drop_table('agents')
    # ### end Alembic commands ###
