"""slack handles per person and per project

Revision ID: 460ed412e342
Revises: 80c776fa3d53
Create Date: 2026-10-06 10:15:05.893203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '460ed412e342'
down_revision: Union[str, Sequence[str], None] = '80c776fa3d53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_slack_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('handle', sa.String(length=128), nullable=True),
    sa.Column('slack_user_id', sa.String(length=32), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('declined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invite_result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_slack_member')
    )
    op.create_index(op.f('ix_project_slack_members_project_id'), 'project_slack_members', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_slack_members_user_id'), 'project_slack_members', ['user_id'], unique=False)
    op.add_column('users', sa.Column('slack_handle', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'slack_handle')
    op.drop_index(op.f('ix_project_slack_members_user_id'), table_name='project_slack_members')
    op.drop_index(op.f('ix_project_slack_members_project_id'), table_name='project_slack_members')
    op.drop_table('project_slack_members')
    # ### end Alembic commands ###
