"""jaws agent identities and connection mode

Revision ID: 5005b2b90e61
Revises: 417056b3738b
Create Date: 2026-10-05 22:36:11.935211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5005b2b90e61'
down_revision: Union[str, Sequence[str], None] = '417056b3738b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('public_key', sa.String(length=64), nullable=True))
    op.add_column('agents', sa.Column('enrol_token_hash', sa.String(length=128), nullable=True))
    op.add_column('agents', sa.Column('enrol_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('agents', sa.Column('enrol_used_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('agents', sa.Column('connection_mode', sa.String(length=16), server_default='callback', nullable=False))
    op.add_column('agents', sa.Column('target_os', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'target_os')
    op.drop_column('agents', 'connection_mode')
    op.drop_column('agents', 'enrol_used_at')
    op.drop_column('agents', 'enrol_expires_at')
    op.drop_column('agents', 'enrol_token_hash')
    op.drop_column('agents', 'public_key')
    # ### end Alembic commands ###
