"""agent reported addresses

Revision ID: 80c776fa3d53
Revises: d56d143dc4e1
Create Date: 2026-10-06 09:37:46.247166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80c776fa3d53'
down_revision: Union[str, Sequence[str], None] = 'd56d143dc4e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('outbound_ip', sa.String(length=45), nullable=True))
    op.add_column('agents', sa.Column('interfaces', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'interfaces')
    op.drop_column('agents', 'outbound_ip')
    # ### end Alembic commands ###
