"""background import jobs

Revision ID: 9a07fccf96d3
Revises: c2c4a6f4f0e9
Create Date: 2026-10-05 00:16:39.419745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a07fccf96d3'
down_revision: Union[str, Sequence[str], None] = 'c2c4a6f4f0e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('fmt', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rows_done', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=True),
    sa.Column('hosts_seen', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_jobs_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_import_jobs_project_status', ['project_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_jobs_status'), ['status'], unique=False)

    # Autogenerate also wanted to "fix" web_addresses.method, round-
    # tripping its server default from "('')" to '' -- the same empty
    # string, written differently by SQLite's schema printer. Dropped
    # deliberately: batch_alter_table on SQLite rebuilds the entire
    # table, and web_addresses holds a proxy history with up to 64 KB
    # of request and response per row. That is a multi-gigabyte rewrite
    # to change nothing.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_jobs_status'))
        batch_op.drop_index('ix_import_jobs_project_status')
        batch_op.drop_index(batch_op.f('ix_import_jobs_project_id'))

    op.drop_table('import_jobs')
    # ### end Alembic commands ###
