"""target kind and project codename

Revision ID: a6a4ea4d07d7
Revises: 732446fb0482
Create Date: 2026-10-05 07:16:30.903542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6a4ea4d07d7'
down_revision: Union[str, Sequence[str], None] = '732446fb0482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codename', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_projects_codename'), ['codename'], unique=False)

    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=16), server_default='host', nullable=False))
        batch_op.create_index(batch_op.f('ix_targets_kind'), ['kind'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_targets_kind'))
        batch_op.drop_column('kind')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_codename'))
        batch_op.drop_column('codename')

    # ### end Alembic commands ###
