"""web address keyed on method too

Revision ID: c2c4a6f4f0e9
Revises: 2ec46c880874
Create Date: 2026-10-04 21:58:39.670558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2c4a6f4f0e9'
down_revision: Union[str, Sequence[str], None] = '2ec46c880874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Rows that predate the method column carry NULL, and the column is
    # about to become part of a unique key where NULLs compare as
    # distinct — which would defeat the deduplication it exists for.
    op.execute("UPDATE web_addresses SET method = '' WHERE method IS NULL")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_addresses', schema=None) as batch_op:
        batch_op.alter_column('method',
               existing_type=sa.VARCHAR(length=12),
               server_default='',
               nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_weburl_target_url'), type_='unique')
        batch_op.create_unique_constraint('uq_weburl_target_method_url', ['target_id', 'method', 'url'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_addresses', schema=None) as batch_op:
        batch_op.drop_constraint('uq_weburl_target_method_url', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_weburl_target_url'), ['target_id', 'url'])
        batch_op.alter_column('method',
               existing_type=sa.VARCHAR(length=12),
               server_default=None,
               nullable=True)

    # ### end Alembic commands ###
