"""agent-written remediation

Revision ID: cef886b349fb
Revises: 11b5687c2b37
Create Date: 2026-10-04 21:23:17.239896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cef886b349fb'
down_revision: Union[str, Sequence[str], None] = '11b5687c2b37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remediation_source', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('remediation_attempts', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('remediation_error', sa.String(length=500), nullable=True))
        batch_op.create_index(batch_op.f('ix_vulns_remediation_source'), ['remediation_source'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vulns_remediation_source'))
        batch_op.drop_column('remediation_error')
        batch_op.drop_column('remediation_attempts')
        batch_op.drop_column('remediation_source')

    # ### end Alembic commands ###
