"""jaws routing modes

A project can run more than one Jaws, and this is how work is spread
across them: mesh, a derived primary, or by operator-declared region.

The interesting part is `agent_tasks.agent_id` becoming nullable. A
null agent means "waiting for the project's policy to choose one",
which is what lets the dispatcher decide on each poll instead of at
queue time -- so a primary can fail over, or a new agent can arrive,
without anything having to re-plan.

The same change moves the foreign key from CASCADE to SET NULL. Those
rows hold the raw output of scans that ran against the client's estate;
deleting an agent should not take the evidence with it.

SQLite cannot drop an unnamed constraint, so the agent_tasks changes go
through batch_alter_table, which rebuilds the table. The autogenerated
version used op.drop_constraint directly and failed on every SQLite
database, which is what the test suite runs on.

Revision ID: d56d143dc4e1
Revises: 5005b2b90e61
Create Date: 2026-10-05 22:50:44.681576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd56d143dc4e1'
down_revision: Union[str, Sequence[str], None] = '5005b2b90e61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

#: Supplied so the existing unnamed FK can be addressed by name on both
#: backends. Postgres named it agent_tasks_agent_id_fkey when the table
#: was created; this convention reproduces that.
CONVENTION = {"fk": "%(table_name)s_%(column_0_name)s_fkey"}


def upgrade() -> None:
    with op.batch_alter_table(
            "agent_tasks", naming_convention=CONVENTION) as b:
        b.add_column(sa.Column("region", sa.String(length=32), nullable=True))
        b.alter_column("agent_id", existing_type=sa.INTEGER(), nullable=True)
        b.drop_constraint("agent_tasks_agent_id_fkey", type_="foreignkey")
        b.create_foreign_key("agent_tasks_agent_id_fkey", "agents",
                             ["agent_id"], ["id"], ondelete="SET NULL")

    op.add_column("agents", sa.Column(
        "priority", sa.Integer(), server_default="100", nullable=False))
    op.add_column("agents", sa.Column(
        "regions", sa.String(length=255), nullable=True))
    op.add_column("projects", sa.Column(
        "jaws_mode", sa.String(length=16), server_default="mesh",
        nullable=False))


def downgrade() -> None:
    op.drop_column("projects", "jaws_mode")
    op.drop_column("agents", "regions")
    op.drop_column("agents", "priority")

    # Going back to a NOT NULL column means the pooled tasks -- the ones
    # that exist only because of this migration -- have nowhere to go.
    # Dropped rather than silently attached to an arbitrary agent, which
    # would put one agent's name on work it never ran.
    op.execute("DELETE FROM agent_tasks WHERE agent_id IS NULL")
    with op.batch_alter_table(
            "agent_tasks", naming_convention=CONVENTION) as b:
        b.drop_constraint("agent_tasks_agent_id_fkey", type_="foreignkey")
        b.create_foreign_key("agent_tasks_agent_id_fkey", "agents",
                             ["agent_id"], ["id"], ondelete="CASCADE")
        b.alter_column("agent_id", existing_type=sa.INTEGER(), nullable=False)
        b.drop_column("region")
