"""index web_addresses.service_id

Revision ID: ebcf99e4d321
Revises: a6a4ea4d07d7
Create Date: 2026-10-05 07:39:25.049803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebcf99e4d321'
down_revision: Union[str, Sequence[str], None] = 'a6a4ea4d07d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_web_addresses_service_id'), ['service_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_web_addresses_service_id'))

    # ### end Alembic commands ###
